-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 15:26:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `first_name` TEXT NOT NULL,
  `middle_name` TEXT NULL DEFAULT NULL,
  `last_name` TEXT NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `college_role` ENUM('student', 'prof', 'ta', 'emp', 'alumni') NOT NULL,
  `profile_image` VARCHAR(255) NOT NULL,
  `year_one_result` BLOB NULL DEFAULT NULL,
  `year_two_result` BLOB NULL DEFAULT NULL,
  `year_three_result` BLOB NULL DEFAULT NULL,
  `year_four_result` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `userID_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`username` ASC),
  INDEX `userID_idx` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lab` (
  `lab_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `location` TEXT NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`lab_id`),
  UNIQUE INDEX `lab_id_UNIQUE` (`lab_id` ASC),
  INDEX `guardian` (`user_id` ASC),
  CONSTRAINT `guardian`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`safe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`safe` (
  `safe_id` INT(10) UNSIGNED NOT NULL,
  `lab_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`safe_id`),
  UNIQUE INDEX `safe_id_UNIQUE` (`safe_id` ASC),
  INDEX `fk_safe_lab1_idx` (`lab_id` ASC),
  CONSTRAINT `fk_safe_lab1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `mydb`.`lab` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`component` (
  `component_id` INT(10) UNSIGNED NOT NULL,
  `safe_id` INT(10) UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `functional` TINYINT(4) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `state` TINYINT(4) NULL DEFAULT NULL,
  `Datasheet_url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`component_id`),
  UNIQUE INDEX `component_id_UNIQUE` (`component_id` ASC),
  INDEX `fk_component_safe1_idx` (`safe_id` ASC),
  CONSTRAINT `fk_component_safe1`
    FOREIGN KEY (`safe_id`)
    REFERENCES `mydb`.`safe` (`safe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borrow` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `component` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `component`),
  INDEX `fk_borrows_Devices1_idx` (`component` ASC),
  CONSTRAINT `borrower`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrows_Devices1`
    FOREIGN KEY (`component`)
    REFERENCES `mydb`.`component` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `post_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `post` TEXT NULL DEFAULT NULL,
  `time` DATETIME NOT NULL,
  `post_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC),
  INDEX `fk_posts_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_posts_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `post_id` INT(10) UNSIGNED NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`, `time`, `user_id`),
  INDEX `post_idx` (`post_id` ASC),
  CONSTRAINT `post`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT(10) UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `department` TEXT NULL DEFAULT NULL,
  `grading` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emails` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `email`),
  CONSTRAINT `fk_emails_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`message_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message_header` (
  `header_id` INT(10) UNSIGNED NOT NULL,
  `user1_id` INT(10) UNSIGNED NOT NULL,
  `user2_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`header_id`, `user1_id`, `user2_id`),
  UNIQUE INDEX `header_id_UNIQUE` (`header_id` ASC),
  INDEX `fk_messages_users_idx` (`user1_id` ASC),
  INDEX `fk_messages_user2_idx` (`user2_id` ASC),
  CONSTRAINT `fk_messages_user1`
    FOREIGN KEY (`user1_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_user2`
    FOREIGN KEY (`user2_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `message_id` INT(11) NOT NULL,
  `header_id` INT(10) UNSIGNED NOT NULL,
  `owner` INT NULL DEFAULT NULL,
  `message` TEXT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`, `header_id`),
  UNIQUE INDEX `message_id_UNIQUE` (`message_id` ASC),
  INDEX `header_id_header_id_message` (`header_id` ASC),
  CONSTRAINT `header_id_header_id_message`
    FOREIGN KEY (`header_id`)
    REFERENCES `mydb`.`message_header` (`header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`notification_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification_header` (
  `header_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`header_id`, `user_id`),
  UNIQUE INDEX `header_id_UNIQUE` (`header_id` ASC),
  INDEX `to_idx` (`user_id` ASC),
  CONSTRAINT `user_id_user_id_Notification`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `notification_id` INT(10) UNSIGNED NOT NULL,
  `header_id` INT(10) UNSIGNED NOT NULL,
  `read` BIT(1) NULL DEFAULT NULL,
  `payload` TEXT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `redirection_url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`notification_id`, `header_id`),
  UNIQUE INDEX `notification_id_UNIQUE` (`notification_id` ASC),
  INDEX `header_id_header_id_notification` (`header_id` ASC),
  CONSTRAINT `header_id_header_id_notification`
    FOREIGN KEY (`header_id`)
    REFERENCES `mydb`.`notification_header` (`header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone_number` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `phone_number` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`user_id`, `phone_number`),
  CONSTRAINT `fk_phones_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`, `position`, `company`),
  CONSTRAINT `fk_position_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `tag_id` INT(10) UNSIGNED NOT NULL,
  `tag` TEXT NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`post_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_tag` (
  `post_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_posts_has_tags_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_posts_has_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`prof_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prof_course` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `course_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`course_id`, `user_id`),
  INDEX `fk_Professor_has_Courses_Courses1_idx` (`course_id` ASC),
  INDEX `fk_Professor/Teacher_Can_Teach_Courses_User1` (`user_id` ASC),
  CONSTRAINT `fk_Professor/Teacher_Can_Teach_Courses_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Courses_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `project_id` INT(10) UNSIGNED NOT NULL,
  `supervisor` INT(10) UNSIGNED NOT NULL,
  `idea` TEXT NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `abstract` TEXT NULL DEFAULT NULL,
  `date_started` DATETIME NOT NULL,
  `date_ended` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`, `supervisor`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  INDEX `professor` (`supervisor` ASC),
  CONSTRAINT `professor`
    FOREIGN KEY (`supervisor`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`project_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_file` (
  `project_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `upload_time` DATETIME NOT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `descreption` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  CONSTRAINT `releated to project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`project_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project_tag` (
  `project_id` INT(10) UNSIGNED NOT NULL,
  `tag_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `tag_id`),
  INDEX `fk_Projects_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_Projects_has_tags_Projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_Projects_has_tags_Projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `skill_id` INT(10) UNSIGNED NOT NULL,
  `skill` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `skill_id_UNIQUE` (`skill_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`student_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_course` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `course_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `course_id`),
  INDEX `fk_Student_have_Courses1` (`course_id` ASC),
  CONSTRAINT `fk_Student_have_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_have_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_degree` INT(11) NOT NULL,
  `year` VARCHAR(255) NOT NULL,
  `subject_code` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_project` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `project_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_User_has_Projects_Projects1_idx` (`project_id` ASC),
  INDEX `fk_User_has_Projects_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Projects_Projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Projects_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_skill` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `skill_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `skill_id`),
  INDEX `fk_Users_has_skills_skills1_idx` (`skill_id` ASC),
  INDEX `fk_Users_has_skills_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Users_has_skills_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
