-- MySQL Script generated by MySQL Workbench
-- Sat May  6 09:02:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Emp` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Emp` (
  `idEmp` INT NOT NULL,
  `num` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` TEXT NOT NULL COMMENT 'Name',
  `middle_name` TEXT NULL COMMENT 'Name',
  `last_name` TEXT NOT NULL COMMENT 'Name',
  `username` VARCHAR(30) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `about` TEXT NULL,
  `college_role` ENUM('student', 'Professor', 'TA', 'Employee', 'Alumni') NOT NULL COMMENT 'can only choose one and only one of the following: student, professor or TA.\nthe choice must be one of them.\n---------------------------------------------------------\nif you want to choose more than one of student, professor or TA then use SET() instead of ENUM()',
  PRIMARY KEY (`user_id`),
  INDEX `userID_idx` (`user_id` ASC),
  UNIQUE INDEX `userID_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lab` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lab` (
  `lab_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL COMMENT 'name of the lab',
  `user_id` INT UNSIGNED NOT NULL COMMENT 'the employee who is responsible for this lab',
  `content` INT UNSIGNED NULL COMMENT 'what is inside this lab',
  `location` TEXT NULL COMMENT 'the loaction of the lab',
  `about` TEXT NULL COMMENT 'a brief description for the lab',
  PRIMARY KEY (`lab_id`),
  UNIQUE INDEX `Contents_UNIQUE` (`content` ASC),
  UNIQUE INDEX `lab_id_UNIQUE` (`lab_id` ASC),
  CONSTRAINT `guardian`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`safe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`safe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`safe` (
  `safe_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`safe_id`, `content`),
  UNIQUE INDEX `safe_id_UNIQUE` (`safe_id` ASC),
  UNIQUE INDEX `content_UNIQUE` (`content` ASC),
  CONSTRAINT `fk_Safe_Labs1`
    FOREIGN KEY (`safe_id`)
    REFERENCES `mydb`.`lab` (`content`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`component` ;

CREATE TABLE IF NOT EXISTS `mydb`.`component` (
  `component_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL COMMENT 'device/component name',
  `functional` TINYINT NOT NULL COMMENT 'is it working or is it damaged',
  `count` INT NULL COMMENT 'how may units are there',
  `state` TINYINT NULL COMMENT 'borrowed(1) or in lab(0)',
  `Datasheet_url` TEXT NULL,
  PRIMARY KEY (`component_id`),
  UNIQUE INDEX `component_id_UNIQUE` (`component_id` ASC),
  CONSTRAINT `fk_component_safe1`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`safe` (`content`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supervisor` INT UNSIGNED NOT NULL COMMENT 'the professor who supervises this project',
  `idea` TEXT NULL COMMENT 'idea of the project',
  `name` TEXT NULL COMMENT 'name of the project',
  `abstract` TEXT NULL COMMENT 'a brief description of the project',
  `date_started` DATETIME NOT NULL COMMENT 'date on which the project started',
  `date_ended` DATETIME NULL COMMENT 'date on which the project ended, if the project is still incomplete this leave it NULL',
  PRIMARY KEY (`project_id`, `supervisor`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  CONSTRAINT `professor`
    FOREIGN KEY (`supervisor`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL COMMENT 'name if the course',
  `about` TEXT NULL COMMENT 'a brief description of the course',
  `department` TEXT NULL COMMENT 'the department that this course falls under its categories',
  `grading` TEXT NULL COMMENT 'how many points are assigned for this course (150,200 ....etc)',
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_course` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'we can use\" Professor/Teacher_Can_Teach_Courses\" table to represent this relationship',
  `course_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `course_id`),
  CONSTRAINT `fk_Student_have_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_have_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prof_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prof_course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prof_course` (
  `user_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`course_id`, `user_id`),
  INDEX `fk_Professor_has_Courses_Courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_Professor_has_Courses_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor/Teacher_Can_Teach_Courses_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id of admin',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `skill_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `skill` TEXT NULL COMMENT 'skill name',
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `skill_id_UNIQUE` (`skill_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_skill` (
  `user_id` INT UNSIGNED NOT NULL,
  `skill_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `skill_id`),
  INDEX `fk_Users_has_skills_skills1_idx` (`skill_id` ASC),
  INDEX `fk_Users_has_skills_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Users_has_skills_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_skills_skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`position` ;

CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `user_id` INT UNSIGNED NOT NULL,
  `position` TEXT NOT NULL COMMENT 'name of the position (ex: construction consultant)',
  `company` TEXT NOT NULL COMMENT 'that company that he/she works in',
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_position_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project_file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project_file` (
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL COMMENT 'the id of the user who uploaded this file',
  `upload_time` DATETIME NOT NULL COMMENT 'date on which the file was uploaded',
  `url` TEXT NULL COMMENT 'url of the file (used it if someone wants to download the file)',
  `descreption` TEXT NULL COMMENT 'a brief description of the file',
  PRIMARY KEY (`project_id`),
  CONSTRAINT `releated to project`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message_header` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message_header` (
  `header_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user1_id` INT UNSIGNED NOT NULL,
  `user2_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`header_id`, `user1_id`, `user2_id`),
  INDEX `fk_messages_users_idx` (`user1_id` ASC),
  INDEX `fk_messages_user2_idx` (`user2_id` ASC),
  UNIQUE INDEX `header_id_UNIQUE` (`header_id` ASC),
  CONSTRAINT `fk_messages_user1`
    FOREIGN KEY (`user1_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_user2`
    FOREIGN KEY (`user2_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification_header` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification_header` (
  `header_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT 'notification of user whose id is\n\n-- each user has a header that contains all of his/hers notifications',
  PRIMARY KEY (`header_id`, `user_id`),
  INDEX `to_idx` (`user_id` ASC),
  UNIQUE INDEX `header_id_UNIQUE` (`header_id` ASC),
  CONSTRAINT `user_id_user_id_Notification`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `post_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL COMMENT 'the OP (original poster)',
  `post` TEXT NULL COMMENT 'the post itself',
  `time` DATETIME NOT NULL COMMENT 'time on which the post was posted',
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `fk_posts_User1_idx` (`user_id` ASC),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC),
  CONSTRAINT `fk_posts_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `post_id` INT UNSIGNED NOT NULL,
  `time` DATETIME NOT NULL COMMENT 'time on which the comment was posted',
  `user_id` INT NOT NULL COMMENT 'user who made the comment\n',
  `comment` TEXT NULL COMMENT 'the comment itself\n',
  INDEX `post_idx` (`post_id` ASC),
  PRIMARY KEY (`post_id`, `time`, `user_id`),
  CONSTRAINT `post`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `tag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` TEXT NOT NULL COMMENT 'the tag itself',
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`borrow` ;

CREATE TABLE IF NOT EXISTS `mydb`.`borrow` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'borrower\n',
  `component` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `component`),
  INDEX `fk_borrows_Devices1_idx` (`component` ASC),
  CONSTRAINT `borrower`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrows_Devices1`
    FOREIGN KEY (`component`)
    REFERENCES `mydb`.`component` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_project` (
  `user_id` INT UNSIGNED NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_User_has_Projects_Projects1_idx` (`project_id` ASC),
  INDEX `fk_User_has_Projects_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_User_has_Projects_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Projects_Projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project_tag` (
  `project_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `tag_id`),
  INDEX `fk_Projects_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_Projects_has_tags_Projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_Projects_has_tags_Projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`post_tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`post_tag` (
  `post_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_posts_has_tags_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_posts_has_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydb`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`emails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`emails` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id of owner',
  `email` TEXT NOT NULL COMMENT 'email itself',
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_emails_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`phone_number` ;

CREATE TABLE IF NOT EXISTS `mydb`.`phone_number` (
  `user_id` INT UNSIGNED NOT NULL COMMENT 'id of user who has this phone number',
  `phone_number` VARCHAR(14) NOT NULL COMMENT 'phone number itself',
  PRIMARY KEY (`user_id`, `phone_number`),
  CONSTRAINT `fk_phones_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `header_id` INT UNSIGNED NOT NULL COMMENT 'this message belongs to header ..',
  `owner` BIT NULL COMMENT 'owner is user1(bit = 0)\nowner is user2(bit = 1)',
  `message` TEXT NULL,
  `time` DATETIME NULL,
  PRIMARY KEY (`message_id`, `header_id`),
  UNIQUE INDEX `message_id_UNIQUE` (`message_id` ASC),
  CONSTRAINT `header_id_header_id_message`
    FOREIGN KEY (`header_id`)
    REFERENCES `mydb`.`message_header` (`header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `header_id` INT UNSIGNED NOT NULL COMMENT 'this notification belongs to header ..',
  `notification_id` INT UNSIGNED NOT NULL,
  `read` BIT NULL COMMENT 'did the reciver read it or not',
  `payload` TEXT NULL COMMENT 'what does the notification say',
  `time` DATETIME NULL COMMENT 'time on which this notification was sent',
  `redirection_url` TEXT NULL COMMENT 'URL of the action(post,comment ...etc) that caused the notification to be sent',
  PRIMARY KEY (`header_id`, `notification_id`),
  UNIQUE INDEX `notification_id_UNIQUE` (`notification_id` ASC),
  CONSTRAINT `header_id_header_id_notification`
    FOREIGN KEY (`header_id`)
    REFERENCES `mydb`.`notification_header` (`header_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
